In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [17]:
df = pd.read_csv('loans_updated.csv')

In [18]:
df.shape

(6000, 24)

In [19]:
df.isnull().sum()

Gender                 0
Age                    0
Education              0
Marital_Status         0
Employment_Status      0
Annual_Income          0
Co_Applicant_Income    0
State                  0
Family_Members         0
Loan_Types             0
Savings_Balance        0
Existing_Loans         0
Home_Ownership         0
Mortgage               0
Loan_Amount            0
Loan_Term              0
Interest_Rate          0
Credit_History         0
Previous_Defaults      0
No_Of_Open_Accounts    0
Missed_Payments        0
Property_Area          0
Property_Value         0
Loan_Approveled        0
dtype: int64

In [24]:
df.sample(5)

,Gender,Age,Education,Marital_Status,Employment_Status,Annual_Income,Co_Applicant_Income,State,Family_Members,Loan_Types,...,Loan_Amount,Loan_Term,Interest_Rate,Credit_History,Previous_Defaults,No_Of_Open_Accounts,Missed_Payments,Property_Area,Property_Value,Loan_Approveled
64,Male,43,Graduate,Married,Employed,180800,0,Maharashtra,1,Business Loan,...,1580330,179,16.59,Good,1,6,3,Semi-urban,3426500,0
2351,Female,65,Graduate,Married,Employed,815400,0,Maharashtra,0,Home Loan,...,2042770,337,6.00,Good,0,5,1,Rural,1058600,0
702,Female,28,Not Graduate,Single,Employed,162900,0,Puducherry,2,Gold Loan,...,186850,8,13.08,Good,1,5,0,Urban,6071500,1
229,Male,29,Graduate,Married,Employed,401400,98300,Nagaland,8,Home Loan,...,3869400,301,9.41,Good,0,9,1,Urban,2403100,0
4496,Male,38,Graduate,Single,Employed,568700,0,Maharashtra,5,Car Loan / Vehicle Loan,...,663510,28,17.50,Bad,0,13,1,Semi-urban,71200,1

In [25]:
df.info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               6000 non-null   object
 1   Age                  6000 non-null   int64
 2   Education            6000 non-null   object
 3   Marital_Status       6000 non-null   object
 4   Employment_Status    6000 non-null   object
 5   Annual_Income        6000 non-null   int64
 6   Co_Applicant_Income  6000 non-null   int64
 7   State                6000 non-null   object
 8   Family_Members       6000 non-null   int64
 9   Loan_Types           6000 non-null   object
 10  Savings_Balance      6000 non-null   int64
 11  Existing_Loans       6000 non-null   int64
 12  Home_Ownership       6000 non-null   object
 13  Mortgage             6000 non-null   object
 14  Loan_Amount          6000 non-null   int64
 15  Loan_Term            6000 non-null   int64
 16  Interest_Rate        6000 non-null   float64
 17  Credit_History       6000 non-null   object
 18  Previous_Defaults    6000 non-null   int64
 19  No_Of_Open_Accounts  6000 non-null   int64
 20  Missed_Payments      6000 non-null   int64
 21  Property_Area        6000 non-null   object
 22  Property_Value       6000 non-null   int64
 23  Loan_Approveled      6000 non-null   int64
dtypes: float64(1), int64(13), object(10)
memory usage: 1.1+ MB

In [29]:
# One Hot Encoding
df = pd.get_dummies(
    df,
    columns=[
        'Gender',
        'Education',
        'Marital_Status',
        'Employment_Status',
        'State',
        'Loan_Types',
        'Home_Ownership',
        'Mortgage',
        'Credit_History',
        'Property_Area'
    ],
    drop_first=True
)

In [22]:
df.columns

Index(['Gender', 'Age', 'Education', 'Marital_Status', 'Employment_Status',
       'Annual_Income', 'Co_Applicant_Income', 'State', 'Family_Members',
       'Loan_Types', 'Savings_Balance', 'Existing_Loans', 'Home_Ownership',
       'Mortgage', 'Loan_Amount', 'Loan_Term', 'Interest_Rate',
       'Credit_History', 'Previous_Defaults', 'No_Of_Open_Accounts',
       'Missed_Payments', 'Property_Area', 'Property_Value',
       'Loan_Approveled'],
      dtype='object')

In [30]:
df.head()

,Age,Annual_Income,Co_Applicant_Income,Family_Members,Savings_Balance,Existing_Loans,Loan_Amount,Loan_Term,Interest_Rate,Previous_Defaults,...,Mortgage_Fixed Deposit,Mortgage_Gold,Mortgage_Home,Mortgage_House,Mortgage_Land/Plot,Mortgage_Other,Mortgage_Vehicle,Credit_History_Good,Property_Area_Semi-urban,Property_Area_Urban
0,23,104200,149700,5,70070,2,889040,301,7.86,0,...,False,False,False,False,True,False,False,True,False,False
1,66,996900,205500,5,198980,1,555600,63,12.10,0,...,False,False,False,False,False,False,False,True,True,False
2,59,537700,0,4,234980,1,260100,26,7.00,0,...,False,False,False,False,False,False,False,True,False,True
3,45,744300,0,3,45020,3,273460,28,12.75,1,...,False,True,False,False,False,False,False,True,False,True
4,45,463100,0,2,98640,1,95660,6,11.54,0,...,False,False,True,False,False,False,False,True,True,False

In [33]:
df.shape

(6000, 85)

In [35]:
X = df.drop(['Loan_Approveled'],axis=1)
y = df['Loan_Approveled']

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [38]:
df['Previous_Defaults'].unique()

array([0, 1, 4, 3, 2, 5])

In [40]:
#Scaling
from sklearn.preprocessing import StandardScaler
num_cols = [
    'Age','Annual_Income','Co_Applicant_Income',
    'Savings_Balance','Existing_Loans',
    'Loan_Amount','Loan_Term',
    ]
scaler = StandardScaler()

In [41]:
df.head()

,Age,Annual_Income,Co_Applicant_Income,Family_Members,Savings_Balance,Existing_Loans,Loan_Amount,Loan_Term,Interest_Rate,Previous_Defaults,...,Mortgage_Fixed Deposit,Mortgage_Gold,Mortgage_Home,Mortgage_House,Mortgage_Land/Plot,Mortgage_Other,Mortgage_Vehicle,Credit_History_Good,Property_Area_Semi-urban,Property_Area_Urban
0,23,104200,149700,5,70070,2,889040,301,7.86,0,...,False,False,False,False,True,False,False,True,False,False
1,66,996900,205500,5,198980,1,555600,63,12.10,0,...,False,False,False,False,False,False,False,True,True,False
2,59,537700,0,4,234980,1,260100,26,7.00,0,...,False,False,False,False,False,False,False,True,False,True
3,45,744300,0,3,45020,3,273460,28,12.75,1,...,False,True,False,False,False,False,False,True,False,True
4,45,463100,0,2,98640,1,95660,6,11.54,0,...,False,False,True,False,False,False,False,True,True,False

In [42]:
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [54]:
y_test

1782    0
3917    0
221     0
2135    0
5224    1
       ..
2522    0
312     0
5887    1
4483    1
2647    1
Name: Loan_Approveled, Length: 1980, dtype: int64

In [55]:
#Stacking
base_learner = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svm',SVC(probability=True, kernel='rbf',random_state=42)),
    ('lr',LogisticRegression(max_iter=1000))
]

In [56]:
meta_learner = LogisticRegression(max_iter=1000)

In [57]:
stacking_CLF = StackingClassifier(
    estimators = base_learner,
    final_estimator = meta_learner,
    cv= 5
)

In [58]:
stacking_CLF.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svm', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [59]:
y_pred = stacking_CLF.predict(X_test)

In [60]:
accuracy_score(y_test, y_pred)

0.8328282828282828

In [61]:
#Bagging
from sklearn.ensemble import RandomForestClassifier

In [62]:
model_RBF = RandomForestClassifier(
    n_estimators = 100,
    max_depth = None,
    random_state=42
)

In [63]:
model_RBF.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [64]:
y_pred = model_RBF.predict(X_test)

In [65]:
accuracy_score(y_test, y_pred)

0.8242424242424242

In [66]:
#Boosting
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [67]:
model_ADA = AdaBoostClassifier(n_estimators=100, random_state=42)

In [68]:
model_ADA.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [70]:
y_pred = model_ADA.predict(X_test)

In [71]:
accuracy_score(y_test, y_pred)

0.8136363636363636

In [72]:
#GradientBoostingClassifier
model_GB = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

In [73]:
model_GB.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [74]:
y_pred = model_GB.predict(X_test)

In [75]:
accuracy_score(y_test, y_pred)

0.8434343434343434

In [76]:
#XGBoost
from xgboost import XGBClassifier

In [77]:
model_XGB = XGBClassifier(n_estimator=100, learning_rate=0.1, random_state=42)

In [78]:
model_XGB.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [14:56:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimator=100,
              n_estimators=None, n_jobs=None, ...)

In [79]:
y_pred = model_XGB.predict(X_test)

In [80]:
accuracy_score(y_test, y_pred)

0.8444444444444444

In [81]:
import joblib

In [83]:
joblib.dump(model_XGB,"model_XGB.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X_train.columns.tolist(),"model_columns.pkl")

['model_columns.pkl']